name: projecthub_ai_app
description: "A new Flutter project."
publish_to: "none"

version: 2.1.0+4

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # For material you.
  dynamic_color: ^1.7.0

  flutter_inappwebview: ^6.1.5
  path_provider: ^2.1.4
  permission_handler: ^11.3.1
  provider: ^6.1.2
  share_plus: ^10.0.2
  # charts_flutter: ^0.9.0
  crypto: ^3.0.5
  package_info_plus: ^8.0.2
  # flutter_icons: ^1.1.0
  flutter_font_icons: ^2.2.7
  flutter_svg: ^2.0.10+1
  mime: ^1.0.6
  url_launcher: ^6.3.0
  cached_network_image: ^3.4.1
  flutter_colorpicker: ^1.1.0
  intl: any
  uuid: ^4.5.0
  collection: any
  context_menus: ^2.0.0+1
  multi_window: ^0.2.0
  sqflite: ^2.3.3+2
  sqflite_common_ffi: ^2.3.3+1
  sqlite3_flutter_libs: ^0.5.24
  window_manager_plus: ^1.0.5
  shared_preferences: ^2.3.3
  path: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

